@host = 127.0.0.1:5001/api/v1
@lonFrom=73.41071023568674
@latFrom=61.239917163896365
@latTo=61.2774852727745
@lonTo=73.36503933069116

### Построение маршрута между двумя точками
GET {{host}}/routes/build/points?developmentId=1&osmId=3488007902

###

### Получение маршрутов до ближайших инфраструктурных объектов
GET {{host}}/objects/find/nearestInfrastructure?objectTypes=hospital&objectTypes=sport&objectTypes=shops&objectTypes=kindergarten&objectTypes=busStop&lon={{lonFrom}}&lat={{latFrom}}

###
GET {{host}}/development/search/board?
    topLeftLon=73.45372857594197&
    topLeftLat=61.25061044995226&
    bottomRightLon=73.45166389831363&
    bottomRightLat=61.25117104755381

###

### Generate infrastructure heatmap
POST {{host}}/infrastructure/heatmap
Content-Type: application/json

{
  "bbox": {
    "topLeftLon": 73.2,
    "topLeftLat": 61.35,
    "bottomRightLon": 73.55,
    "bottomRightLat": 61.15
  },
  "cellSize": 500,
  "weights": {
    "hospital": 7,
    "sport": 4,
    "shops": 3,
    "kindergarten": 6,
    "bus_stop": 2,
    "school": 9
  }
}
