@host = 127.0.0.1:8080/api/v1
@lonFrom=73.41071023568674
@latFrom=61.239917163896365
@latTo=61.2774852727745
@lonTo=73.36503933069116

### Построение маршрута между двумя точками
GET {{host}}/routes/build/points?developmentId=1&osmId=3488007902

###

### Получение маршрутов до ближайших инфраструктурных объектов
GET {{host}}/objects/find/nearestInfrastructure?objectTypes=hospital&objectTypes=sport&objectTypes=shops&objectTypes=kindergarten&objectTypes=busStop&lon={{lonFrom}}&lat={{latFrom}}

###
GET {{host}}/development/search/board?
    topLeftLon=73.45372857594197&
    topLeftLat=61.25061044995226&
    bottomRightLon=73.45166389831363&
    bottomRightLat=61.25117104755381

###
