openapi: 3.0.3
servers:
  - url: 'https://127.0.0.1:8080'
info:
  version: 1.0.0
  title: Real estate insight
paths:
  /:
    get:
      operationId: indexPage
      responses:
        200:
          description: Index page'
          content:
            text/html:
              schema:
                type: string
        500:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /routes/build/points:
    get:
      summary: Build a route between points
      description: Build a route between points
      operationId: buildRoutesByPoints
      parameters:
        - name: latFrom
          in: query
          schema:
            type: number
        - name: lonFrom
          in: query
          schema:
            type: number
        - name: latTo
          in: query
          schema:
            type: number
        - name: lonTo
          in: query
          schema:
            type: number
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true # GeoJson
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /objects/find/nearestInfrastructure:
    get:
      summary: Search for nearby infrastructure facilities
      description: Search for nearby infrastructure facilities
      operationId: objectsFindNearestInfrastructure
      parameters:
        - name: lat
          in: query
          schema:
            type: number
        - name: lon
          in: query
          schema:
            type: number
        - name: objectTypes
          in: query
          description: 'Necessary objects'
          schema:
            type: array
            items:
              type: string
              enum:
                - hospital
                - sport
                - shops
                - kindergarten
                - busStop
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true # GeoJson
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"

components:
  schemas:
    error:
      type: object
      properties:
        status:
          type: string
          enum:
            - not-found
            - bad-request
            - internal-error
            - unauthorized
        error:
          description: Ошибка
          type: object
          properties:
            code:
              description: Код ошибки
              type: integer
            message:
              description: Сообщение об ошибке
              type: string